apiVersion: v1
kind: ConfigMap
data:
  KAFKA_SERVER: "udaconnect-kafka-broker-0.udaconnect-kafka-broker-headless.default.svc.cluster.local:9092"
  KAFKA_TOPIC_NAME: "location-ingestion-data"
metadata:
  name: kafka-env