apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-ingester
  name: udaconnect-location-ingester
spec:
  ports:
    - name: "5005-5005"
      nodePort: 30005
      port: 5005
      targetPort: 5005
  selector:
    app: udaconnect-location-ingester
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-ingester
  name: udaconnect-location-ingester
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-ingester
  template:
    metadata:
      labels:
        service: udaconnect-location-ingester
    spec:
      containers:
        - image: mppcosta/udaconnect-location-ingester:latest
          name: udaconnect-location-ingester
          imagePullPolicy: Always
          env:
            - name: KAFKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: KAFKA_SERVER
            - name: KAFKA_TOPIC_NAME
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: KAFKA_TOPIC_NAME
      restartPolicy: Always