swagger: '2.0'
basePath: /
consumes:
- application/json
info:
  title: UdaConnect API
  version: 0.1.0
paths:
  /api/locations:
    get:
      operationId: get_location_resource
      responses:
        '200':
          description: Success
      tags:
      - UdaConnect
    parameters:
    - description: Unique ID for a given Location
      in: query
      name: location_id
      type: string
    post:
      operationId: post_location_resource
      responses:
        '200':
          description: Success
      tags:
      - UdaConnect
  /api/locations/{location_id}:
    get:
      operationId: get_location_resource
      responses:
        '200':
          description: Success
      tags:
      - UdaConnect
    parameters:
    - description: Unique ID for a given Location
      in: path
      name: location_id
      required: true
      type: string
    post:
      operationId: post_location_resource
      responses:
        '200':
          description: Success
      tags:
      - UdaConnect
  /api/persons:
    get:
      operationId: get_persons_resource
      responses:
        '200':
          description: Success
      tags:
      - UdaConnect
    post:
      operationId: post_persons_resource
      responses:
        '200':
          description: Success
      tags:
      - UdaConnect
  /api/persons/{person_id}:
    get:
      operationId: get_person_resource
      responses:
        '200':
          description: Success
      tags:
      - UdaConnect
    parameters:
    - description: Unique ID for a given Person
      in: path
      name: person_id
      required: true
      type: string
  /api/persons/{person_id}/connection:
    get:
      operationId: get_connection_data_resource
      responses:
        '200':
          description: Success
      tags:
      - UdaConnect
    parameters:
    - description: Proximity to a given user in meters
      in: query
      name: distance
      type: string
    - description: Upper bound of date range
      in: query
      name: end_date
      type: string
    - description: Lower bound of date range
      in: query
      name: start_date
      type: string
    - in: path
      name: person_id
      required: true
      type: string
produces:
- application/json
responses:
  MaskError:
    description: When any error occurs on mask
  ParseError:
    description: When a mask can't be parsed
tags:
- description: Connections via geolocation.
  name: UdaConnect
